Add Events to the website
pycascades/www.pycascades.com pull request #104
Opened 2019-12-12 15:59 UTC by ericholscher

This includes Sprints, Lightning talks, and Open Spaces.

**This also now includes a blog post announcing these events.** We can ship that week before xmas, if it makes sense.

2019-12-17 18:04 UTC, EstiShay requested changes
I skimmed some of it because I don't have time to read it all in depth right now, but I'll try to find more time to review later.

2019-12-17 18:04 UTC, EstiShay commented on content/news/4-events-and-activities/contents.lr
> +* **Welcome reception.** The `meet-and-greet event </reception/>` will be held on Friday from *5pm-8pm*. You can pick up your badge so you don't have to wait in line in the morning. and enjoy a coupl
> You can pick up your badge so you don't have to wait in line in the morning. and enjoy a couple of drinks and snacks on us.

Replace with:
You can pick up your badge so you don't have to wait in line in the morning, and enjoy some refreshments on us.
(Replaces the period with a comma, removes the suggestion of alcohol.)

> great chance to meet your fellow documentarians before the conference starts

Should probably replace with "fellow Pythonistas."

What do you think about adding a note about having the Open Spaces sign up board at the reception so you can start drumming up interest in the topics you'd like to discuss?

2019-12-17 18:04 UTC, EstiShay commented on content/news/4-events-and-activities/contents.lr
> +Thank you so much to all those who applied to volunteer so far! There are still a few spots available, and if you volunteer for two or more shifts we will provide you with a free conference ticket.
1. Remove "a few spots available" - we haven't even begun the volunteer advertising yet, so we need to be more aggressively recruiting.
2. PyCascades isn't providing free tickets for volunteers, so that needs to be removed.

2019-12-17 18:04 UTC, EstiShay commented on content/news/4-events-and-activities/contents.lr
> +There is plenty to do during the conference and volunteers are essential to the success of all our events! To register as a volunteer for the conference, please read and fill out the `Call for Volunt
Change "please read and fill out the Call for Volunteers" — WTD phrasing? — to something like "Sign up to volunteer" and maybe include something about receiving a volunteer t-shirt so you can show off that you support the community.

2019-12-17 18:04 UTC, EstiShay commented on content/news/4-events-and-activities/contents.lr
> +Every year we are thrilled to welcome new pythonistas into our community. This is your friendly reminder that we have resources on our website and on Slack to help you prepare for your first trip to
I think "Pythonistas" needs to be capitalized.

2019-12-17 18:04 UTC, EstiShay commented on content/news/4-events-and-activities/contents.lr
> +In this update, we're happy to share with you the different events and activities that will be available as a part of the conference, remind you about volunteering, and to ask you to grab your ticket
Might want to highlight here that we have a new activity, Open Spaces, right here in the first sentence to catch the attention of past attendees who might assume they already know what we have to offer.

2019-12-17 18:04 UTC, EstiShay commented on content/reception/contents.lr
> +We encourage everyone to drop by on Friday evening for the conference reception. You’ll have a chance to get acquainted with each other over some drinks and snacks, and pick up your badge so you can
Again, replace "drinks and snacks" with "refreshments" since we're a dry conference.

2019-12-21 22:19 UTC, theacodes approved these changes
I fixed up the blog post page - it was missing the date. This looks good to me. @nnja please merge if it looks okay to you.

2020-01-04 23:34 UTC, nnja commented
Fixed merge conflicts and commented out the section on contributing to sprints, as I don't think we've settled on if we want a separate welcome wagon site or not.

2020-01-04 23:40 UTC, theacodes approved these changes

2020-01-04 23:40 UTC, theacodes commented on content/news/4-events-and-activities/contents.lr
> +date: 2019-12-21
This date needs to be updated now

2020-01-04 23:52 UTC, merged