Add welcome wagon to 2020 site
pycascades/www.pycascades.com pull request #105
Opened 2019-12-12 17:51 UTC by ericholscher

This is 80% done. There's a couple sections I commented out, but I think it's better than nothing.

2019-12-12 17:55 UTC, nnja requested changes
Few sections that can be left out, otherwise lgtm

2019-12-12 17:55 UTC, nnja commented on content/welcome-wagon/contents.lr
> +    Contribute
This repo https://github.com/pycascades/welcome-wagon-2020 doesn't exist yet. Remove this section for the time being?

2019-12-12 17:55 UTC, nnja commented on content/welcome-wagon/contents.lr
> +    **Where is everything?**
Update the venue information, and remove everything else?

2019-12-12 17:55 UTC, nnja commented on content/welcome-wagon/contents.lr
> +    **How should I get around?**
Remove this section?

2019-12-12 17:55 UTC, nnja commented on content/welcome-wagon/contents.lr
> +The weather forecast for the weekend is a high of 42°F (6°C) with a
Remove this paragraph

2019-12-12 17:55 UTC, nnja commented on content/welcome-wagon/contents.lr
> +   talks <https://www.pycascades.com/talks/>`_.
this 404s for now

2019-12-12 18:01 UTC, nnja approved these changes
apparently I don't know how comments in rst work. lgtm. 👍

2019-12-16 09:21 UTC, ericholscher commented
@nnja yea, it's annoying that GH won't syntax highlight it because it's `.lr` -- nobody should know RST syntax by heart :D

2019-12-17 01:39 UTC, EstiShay commented on content/welcome-wagon/contents.lr
> +- *Quiet room*: In the SunSet room on the first floor near the main auditorium.
`Sunset` not `SunSet`.

2019-12-17 01:39 UTC, EstiShay commented on content/welcome-wagon/contents.lr
> +Code of Conduct
Maybe hold off on this part until Mariatta can check it? This last year's hotline number; will that be the same this year? And I'd like to be listed, but we don't have a temporary number set up for me yet and I wouldn't want it on the website until right before the conference.

2019-12-17 11:46 UTC, ericholscher commented on content/welcome-wagon/contents.lr
> +Code of Conduct
Commented it out for now 👍

2019-12-21 22:22 UTC, theacodes commented on content/welcome-wagon/contents.lr
> +Code of Conduct
I can reserve us a number from conducthotline.com whenever, and it can be inactive until we turn it on.

2020-01-04 23:11 UTC, merged